### ISSUE TITLE
RuntimeError: CUBLAS_STATUS_INVALID_VALUE in lidar_model forward pass during training

### ISSUE THREAD

**Issue by superleo111** [jingGM/DTG#5]
Hi, thank you for your amazing work on this project! I've been trying to train the model, but I encountered an issue. Here's the error I got:
```
RuntimeError: CUDA error: CUBLAS_STATUS_INVALID_VALUE when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)`
Traceback (most recent call last):
  File "/home/hwc/DTG/main.py", line 15, in <module>
    trainer.run()
  File "/home/hwc/DTG/src/train.py", line 374, in run
    self.run_epoch()
  File "/home/hwc/DTG/src/train.py", line 330, in run_epoch
    output_dict = self.step(data_dict=data_dict)
  File "/home/hwc/DTG/src/train.py", line 289, in step
    output_dict = self.model(data_dict, sample=False)
  File "/home/hwc/miniconda3/envs/hn/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/hwc/DTG/src/models/model.py", line 35, in forward
    observation = self.perception(lidar=input_dict[DataDict.lidar], vel=input_dict[DataDict.vel],
  File "/home/hwc/miniconda3/envs/hn/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/hwc/DTG/src/models/perception.py", line 58, in forward
    lidar_fts = self.lidar_model(lidar)  # B x 512
  File "/home/hwc/miniconda3/envs/hn/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/hwc/DTG/src/models/perception.py", line 32, in forward
    output = self.conv(image)
  File "/home/hwc/miniconda3/envs/hn/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/hwc/miniconda3/envs/hn/lib/python3.10/site-packages/torch/nn/modules/container.py", line 139, in forward
    input = module(input)
  File "/home/hwc/miniconda3/envs/hn/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/hwc/miniconda3/envs/hn/lib/python3.10/site-packages/torch/nn/modules/linear.py", line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: CUDA error: CUBLAS_STATUS_INVALID_VALUE when calling `cublasSgemm( handle, opa, opb, m, n, k, &alpha, a, lda, b, ldb, &beta, c, ldc)`
```
Traceback (most recent call last): File "/home/hwc/DTG/main.py", line 11, in <module> trainer.run() ... RuntimeError: CUDA error: CUBLAS_STATUS_INVALID_VALUE when calling cublasSgemm(...)
**Steps to Reproduce**

1. Prepare the dataset and place it under 

   ```
   data_sample/
   ```

   :

   ```
   data_sample/
       ├── data.pkl
       └── data_folder/
   main.py
   ```

2. Run the command:

   ```bash
   export CUDA_VISIBLE_DEVICES=1
   python main.py --wandb_api=<your_api> --generator_type=0 --diffusion_model=0 --crnn_type=0
   ```

3. The error occurs during the first training epoch in the `lidar_model` forward pass.

**Environment**

- OS: Ubuntu 20.04
- Python: 3.10
- CUDA: 11.3
- PyTorch: 1.13.1+cu113
- GPU: NVIDIA RTX A6000

I’ve tried reducing the batch size and debugging the input data, but the issue persists. The input tensor shapes seem correct

If you could provide any insights or suggestions, I would really appreciate it. Let me know if additional details are needed. Thank you so much for your time!

**Comment by superleo111** [comment]
print cfgs.__dict__
{'name': 'hnav', 'wandb_api': , 'only_model': False, 'output_dir': './results', 'snapshot': '', 'max_epoch': 30, 'evaluation_freq': 5, 'train_time_steps': 32, 'scheduler': 'cosine', 'lr': 2e-05, 'weight_decay': 0, 'lr_t0': 1, 'lr_tm': 30, 'lr_min': 1e-08, 'traversability_threshold': 1e-07, 'gpus': {'channels_last': False, 'local_rank': 0, 'sync_bn': False, 'no_ddp_bb': False, 'device': 'cuda', 'split_bn': False}, 'data': {'name': 'hnav', 'root': 'data_sample', 'batch_size': 1, 'num_workers': 1, 'shuffle': False, 'distributed': False, 'training_data_percentage': 0.95, 'lidar_cfg': {'threshold': 100, 'channels': 16, 'horizons': 1824, 'angle_range': 200}, 'vel_num': 10, 'imu_num': 0}, 'model': {'generator_type': 0, 'cvae': {'activation_func': None, 'rnn_type': 0, 'perception_in': 770, 'vae_zd': 512, 'vae_output_threshold': 1, 'paths_num': 5, 'waypoints_num': 16, 'waypoint_dim': 2, 'estimate_traversability': True, 'fix_first': False, 'cvae_file': None}, 'diffusion': {'beta_start': 0.0001, 'beta_end': 0.02, 'beta_schedule': 'squaredcos_cap_v2', 'clip_sample': True, 'clip_sample_range': 1.0, 'num_train_timesteps': 100, 'variance_type': 'fixed_small', 'perception_in': 770, 'diffusion_zd': 512, 'waypoint_dim': 2, 'waypoints_num': 16, 'rnn_type': 0, 'rnn_output_threshold': 1, 'diffusion_step_embed_dim': 256, 'down_dims': [512, 1024, 2048], 'kernel_size': 5, 'cond_predict_scale': True, 'use_traversability': True, 'estimate_traversability': True, 'traversable_steps': 10, 'traversable_steps_buffer': 5, 'n_groups': 8, 'model_type': 'crnn', 'use_all_paths': False, 'sample_times': -1, 'crnn': {'type': 'gru', 'waypoint_num': 16}}, 'perception': {'fix_perception': False, 'vel_dim': 20, 'vel_out': 256, 'lidar_out': 512, 'lidar_norm_layer': False, 'lidar_num': 3}, 'scale_waypoints': 1.0}, 'loss': {'train_poses': False, 'scale_waypoints': 1.0, 'use_traversability': True, 'distance_type': 'average', 'distance_ratio': 10.0, 'last_ratio': 2.0, 'vae_kld_ratio': 1.0, 'traversability_ratio': 10.0, 'generator_type': 0, 'traversability_estimation_reconstruct_ratio': 10.0, 'root': 'data_sample', 'map_resolution': 0.1, 'map_range': 300, 'image_separate': 20, 'output_dir': None}}
